### ISSUE TITLE
network access request de catre NetworkLibrary

### ISSUE THREAD

**Issue by aplicatii-romanesti** [aplicatii-romanesti/imbunatatiri_si_problemele#5]
FBReader 2.6.28 (2062810) exception report

Package:org.geometerplus.zlibrary.ui.android.aplicatii.romanesti
Model:WAS-LX1
Device:HWWAS-H
Product:WAS-LX1
Manufacturer:HUAWEI
Version:8.0.0
java.lang.SecurityException: ConnectivityService: Neither user 10173 nor current process has android.permission.ACCESS_NETWORK_STATE.
        at android.os.Parcel.readException(Parcel.java:1946)
        at android.os.Parcel.readException(Parcel.java:1892)
        at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1216)
        at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:903)
        at org.geometerplus.android.fbreader.network.auth.AndroidNetworkContext.getActiveNetworkInfo(AndroidNetworkContext.java:115)
        at org.geometerplus.android.fbreader.network.auth.AndroidNetworkContext.perform(AndroidNetworkContext.java:120)
        at org.geometerplus.zlibrary.core.network.ZLNetworkContext.downloadToFile(ZLNetworkContext.java:127)
        at org.geometerplus.zlibrary.core.network.ZLNetworkContext.downloadToFile(ZLNetworkContext.java:123)
        at org.geometerplus.fbreader.network.opds.OPDSLinkReader.loadOPDSLinks(OPDSLinkReader.java:82)
        at org.geometerplus.fbreader.network.NetworkLibrary.initialize(NetworkLibrary.java:288)
        at org.geometerplus.android.fbreader.ProcessHyperlinkAction$4.run(ProcessHyperlinkAction.java:187)
        at java.lang.Thread.run(Thread.java:784)

**Comment by aplicatii-romanesti** [comment]
Package:org.geometerplus.zlibrary.ui.android.aplicatii.romanesti
Model:VFD 720
Device:VFD720
Product:Smart_N9
Manufacturer:Vodafone
Version:8.1.0
java.lang.SecurityException: ConnectivityService: Neither user 10141 nor current process has android.permission.ACCESS_NETWORK_STATE.
	at android.os.Parcel.readException(Parcel.java:2005)
	at android.os.Parcel.readException(Parcel.java:1951)
	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1233)
	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:830)
	at org.geometerplus.android.fbreader.network.auth.AndroidNetworkContext.getActiveNetworkInfo(AndroidNetworkContext.java:115)
	at org.geometerplus.android.fbreader.network.auth.AndroidNetworkContext.perform(AndroidNetworkContext.java:120)
	at org.geometerplus.zlibrary.core.network.ZLNetworkContext.downloadToFile(ZLNetworkContext.java:127)
	at org.geometerplus.zlibrary.core.network.ZLNetworkContext.downloadToFile(ZLNetworkContext.java:123)
	at org.geometerplus.fbreader.network.opds.OPDSLinkReader.loadOPDSLinks(OPDSLinkReader.java:82)
	at org.geometerplus.fbreader.network.NetworkLibrary.initialize(NetworkLibrary.java:288)
	at org.geometerplus.android.fbreader.ProcessHyperlinkAction$4.run(ProcessHyperlinkAction.java:187)
	at java.lang.Thread.run(Thread.java:764)
